source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'WellBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WellBlog
  pod 'Alamofire'
  pod 'Moya'
  pod 'SnapKit'

  target 'WellBlogTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
